### ISSUE TITLE
Error Message "Uncaught (in promise)"

### ISSUE THREAD

**Issue by weijye91** [RubaXa/Ply#6]
Hi RubaXa,
Thanks for the cool library.

I got an error message in the browser that goes like this 
![untitled](https://cloud.githubusercontent.com/assets/8890603/8152314/2689ce20-134e-11e5-9c5a-cb623d70279f.png)
when I'm clicked on the cancel button in the confirm dialogue. Here's the code:
```
Ply.dialog("confirm",
             {
                 effect: "3d-sign",
                 onaction: function (ui) {
                     if (ui.state) {
                         // Clicked "OK
                         console.log('OK');
                         alert('OK');
                     }
                              
                     if (ui.by === 'cancel') {
                         // Clicked "Cancel"
                         //   details: `ui.by` — "cancel", "overlay", "esc", "x"
                         console.log('Clicked cancel');
                     }
               }
```

**Comment by RubaXa** [comment]
This is the correct work:
![Promise](https://dl.dropbox.com/s/ty98gochlczpgw8/Screenshot%202015-06-15%2008.47.45.png?dl=0)

**Comment by weijye91** [comment]
I'm sorry I don't get it. Why am I getting that error message? does the onaction function return a promise object? If that is the case, how come the ui.state (Clicked ok on the OK button) does not prompt the error message.

**Comment by stevenwanderski** [comment]
I had the same confusion and @RubaXa's response did not help.

I am now using Ply like this:

```
Ply.dialog("confirm", "Do you like it?")
      .then((ui) => {
        console.log('go!');
      })
      .catch((ui) => {
        console.log('cancel');
      });
```

This results in no errors. @weijyewang hope this helps!

**Comment by jpope19** [comment]
This still hasn't helped. I feel like i've tried everything:

`    Ply.dialog('prompt', {
      title: 'Add',
      form: {
        name: 'name', 
        jetskis: {hint: 'Number of jetskis', type: 'number', min: 1, max: 5}, 
        time: {hint: 'Rental Time', type: 'time', step: 900, min: '00:00', max: '02:00'}
      }
    })
    .done(function(ui) {
      console.log("done");
    })
    .fail(function(ui) {
      console.log("fail");
    })
    .always(function(ui) {
      var el = document.createElement('li');
      el.innerHTML = ui.data.name + '<i class="js-remove">✖</i>';
      editableList.el.appendChild(el);
    })
    .catch(function(e) {
      console.log("catch");
    });`
