### ISSUE TITLE
Callbacks not working with exemples

### ISSUE THREAD

**Issue by TitoVince35** [RubaXa/Ply#8]
Hello,
I have tryed the exemple code

```
Ply.dialog('confirm','are you ok?')
          .done(function(ui){
            console.log("Done");
          })
```

And I get this error:
`TypeError: Ply.dialog(...).done is not a function`

In fact, all the dialogs show like marvels but no chained function seems to work (always, done, fail...)

**Comment by RubaXa** [comment]
- https://dl.dropbox.com/s/7kxbo1kk71qveue/Screenshot%202016-02-12%2013.34.14.png?dl=0
- https://dl.dropbox.com/s/lpunjvw4zwqezcr/Screenshot%202016-02-12%2013.34.20.png?dl=0

**Comment by TitoVince35** [comment]
Thanks for you quick answer. I'm also using jQuery, but I didn't get Promise.
Now this is done:

```
<script type="text/javascript" src="lib/js/Promise.js"></script>
<script type="text/javascript" src="vendor/RabaXa/Ply/Ply.min.js"></script>
```

Still getting the same... and Promise does not speak to the console!

**Comment by TitoVince35** [comment]
Got it!
In fact it's ok if I use the same exact script as you
`<script type="text/javascript" src="http://rubaxa.github.io/Ply/Ply.min.js"></script>`
It fails if I download your 0.3.0 release.
Maybe I should just clone your master branch if I want to use Ply localy.
